services:
  lambda_py38:
    image: "lambshm/python3.8-test"
    ipc: none
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "9000:8080"

    build:
      context: '..'
      dockerfile: 'config/Dockerfile.test'
      args:
        source: "lambshm/python3.8"