services:
  runtime:
    image: "${IMAGE_NAME}-test"
    ipc: none
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "9000:8080"

    build:
      context: '..'
      dockerfile: 'config/Dockerfile.test'
