name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose --ansi never -f config/docker-compose.yml build --progress plain lambda_py38
    - name: Build the test image
      run: docker compose --ansi never -f config/docker-compose.yml -f config/docker-compose.test.yml build --progress plain
    - name: Test the image
      run: docker compose --ansi never  -f config/docker-compose.yml -f config/docker-compose.test.yml run --entrypoint /bin/sh --rm lambda_py38 -c 'mkdir /tmp/shm && python /var/task/lambda_handler.py'
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push image
      run: ./scripts/upload-to-github.sh "${{ github.repository_owner }}" "${{ github.ref }}"

