name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install venv
      run: python -m pip install -r dev-requirements.txt
    - name: Download
      run: python -m invoke download
    - name: Build
      run: python -m invoke build
    - name: Test
      run: python -m invoke test
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push image
      run: ./scripts/upload-to-github.sh "${{ github.repository_owner }}" "${{ github.ref }}"

