name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG_CODEGEN: 'yes'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install venv
      run: python -m pip install -r dev-requirements.txt
    - name: Download
      run: invoke download
    - name: Build
      run: invoke build
    - name: Test
      run: invoke test
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push image
      run: invoke upload --repo-prefix='${{ github.repository_owner }}' --build-ref='${{ github.ref }}'

